stages:
    - regression

Chrome:
  stage: regression
  image: selenium/standalone-chrome:latest
  before_script:
    - $MAVEN_HOME/bin/mvn clean
    - mvn compile
  script:
    - mvn clean test -DtestngFile="testng.xml"
