
stages:
  - build
  - regression

Build:
  stage: build
  image: maven:3-jdk-11

Chrome:
  stage: regression
  image: selenium/standalone-chrome:latest
  before_script:
    - mvn compile
  script:
    - mvn clean test -DtestngFile="testng.xml"
