image: maven:3-jdk-11
stages:
    - regression

Chrome:
  stage: regression
  image: selenium/standalone-chrome:latest
  before_script:
    - apt install maven:3-jdk-11
    - mvn compile
  script:
    - mvn clean test -DtestngFile="testng.xml"
