version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.3.0-20220726
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_OVERIDE_MAX_INSTANCES=true
      - SE_NODE_MAX_SESSIONS=20
      - SE_NODE_MAX_INSTANCES=20
      - SE_NODE_BROWSER_TIMEOUT=90
    volumes:
      - ./target/downloads:/home/seluser/Downloads

  edge:
    image: selenium/node-edge:4.3.0-20220726
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_OVERIDE_MAX_INSTANCES=true
      - SE_NODE_MAX_SESSIONS=20
      - SE_NODE_MAX_INSTANCES=20

  firefox:
    image: selenium/node-firefox:4.3.0-20220726
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_OVERIDE_MAX_INSTANCES=true
      - SE_NODE_MAX_SESSIONS=20
      - SE_NODE_MAX_INSTANCES=20

  selenium-hub:
    image: selenium/hub:4.3.0-20220726
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"